#!/bin/bash
git diff --quiet && git diff --cached --quiet
status=$?
if test $status -ne 0
then
    echo "+uncommitted"
    grep -q "uncommitted" mads_gitversion.c
    status=$?
    if test $status -ne 0
    then
	rm -f mads_gitversion.c
    fi
fi
