#  -*- mode: cmake -*-
message(STATUS "Installing LibMathEvaL (${LIBMATHEVAL_VERSION})")
if( EXISTS ${TPL_REPO_DIR}/${LIBMATHEVAL_ARCHIVE_FILE} )
	message(STATUS "LibMathEvaL is available in the TPL's repository for MADS (${TPL_REPO_DIR}/${LIBMATHEVAL_ARCHIVE_FILE})" )
	set(LIBMATHEVAL_URL ${TPL_REPO_DIR}/${LIBMATHEVAL_ARCHIVE_FILE})
elseif( EXISTS ${TPL_DOWNLOAD_DIR}/${LIBMATHEVAL_ARCHIVE_FILE} )
	message(STATUS "LibMathEvaL already downloaded (${TPL_DOWNLOAD_DIR}/${LIBMATHEVAL_ARCHIVE_FILE})" )
	set(LIBMATHEVAL_URL ${TPL_DOWNLOAD_DIR}/${LIBMATHEVAL_ARCHIVE_FILE})
else()
	message(STATUS "LibMathEvaL will be downloaded" )
endif()

ExternalProject_Add(
	libmatheval
	DOWNLOAD_DIR  ${TPL_DOWNLOAD_DIR}
	DOWNLOAD_NAME ${LIBMATHEVAL_ARCHIVE_FILE}
	URL           ${LIBMATHEVAL_URL}
	PREFIX        libmatheval-${LIBMATHEVAL_VERSION}
	CONFIGURE_COMMAND autoreconf -fi && ./configure CC=${CMAKE_C_COMPILER} CXX=${CMAKE_CXX_COMPILER} --prefix=${TPL_INSTALL_PREFIX} WORKING_DIRECTORY ${SOURCE_DIR}
	BUILD_COMMAND     make
	BUILD_IN_SOURCE   1
	INSTALL_DIR      ${TPL_INSTALL_PREFIX}
	INSTALL_COMMAND  make install
)
