PKG_CHECK_MODULES(PC_LibYaml yaml)
SET(LibYaml_DEFINITIONS ${PC_LibYaml_CFLAGS_OTHER})

FIND_LIBRARY(LIBYAML_LIBRARY
  NAMES libyaml yaml
  PATHS ${LIBYAML_LIBRARIES}
)

FIND_PATH(LIBYAML_INCLUDE_DIR
  NAMES yaml.h
  PATHS ${LIBYAML_INCLUDE_DIRS} ${LIBYAML_INCLUDE_DIR}
)

SET(LIBYAML_INCLUDE_DIRS "${LIBYAML_INCLUDE_DIR}")
SET(LIBYAML_LIBRARIES "${LIBYAML_LIBRARY}")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibYAML DEFAULT_MSG LIBYAML_LIBRARIES LIBYAML_INCLUDE_DIRS)
MARK_AS_ADVANCED( LIBYAML_LIBRARY LIBYAML_INCLUDE_DIR )
