find_package(PkgConfig)
pkg_check_modules(PC_LIBYAML QUIET libyaml)
set(LIBYAML_DEFINITIONS ${PC_LIBYAML_CFLAGS_OTHER})

FIND_LIBRARY(LIBYAML_LIBRARY
  NAMES libyaml
  PATHS ${LIBYAML_LIBRARIES} ${PROJECT_SOURCE_DIR}/tpls/include
)

FIND_PATH(LIBYAML_INCLUDE_DIR
  NAMES yaml.h
  PATHS ${LIBYAML_INCLUDE_DIRS} ${LIBYAML_INCLUDE_DIR} ${PROJECT_SOURCE_DIR}/tpls/lib
)

SET(LIBYAML_INCLUDE_DIRS "${LIBYAML_INCLUDE_DIR}")
SET(LIBYAML_LIBRARIES "${LIBYAML_LIBRARY}")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibYAML DEFAULT_MSG LIBYAML_LIBRARIES LIBYAML_INCLUDE_DIRS)
MARK_AS_ADVANCED( LIBYAML_LIBRARY LIBYAML_INCLUDE_DIR )
