PKG_CHECK_MODULES(PC_GLIB2 glib-2.0)
SET(GLIB2_DEFINITIONS ${PC_GLIB2_CFLAGS_OTHER})

FIND_PATH(GLIB2_INCLUDE_DIR NAMES glib.h
   HINTS
   ${PC_GLIB2_INCLUDEDIR}
   ${PC_GLIB2_INCLUDE_DIRS}
   )

FIND_LIBRARY(GLIB2_LIBRARIES NAMES glib-2.0
   HINTS
   ${PC_GLIB2_LIBDIR}
   ${PC_GLIB2_LIBRARY_DIRS}
   )

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GLIB2 DEFAULT_MSG GLIB2_LIBRARIES)
MARK_AS_ADVANCED(GLIB2_INCLUDE_DIR GLIB2_LIBRARIES GLIB2_XMLLINT_EXECUTABLE)
