FIND_PACKAGE(PkgConfig)
PKG_CHECK_MODULES(PC_GSL gsl)
SET(GSL_DEFINITIONS ${PC_GSL_CFLAGS_OTHER})

FIND_PATH(GSL_INCLUDE_DIR NAMES gsl.h
   HINTS
   ${PC_GSL_INCLUDEDIR}
   ${PC_GSL_INCLUDE_DIRS}
   PATH_SUFFIXES gsl
   )

FIND_LIBRARY(GSL_LIBRARIES NAMES gsl
   HINTS
   ${PC_GSL_LIBDIR}
   ${PC_GSL_LIBRARY_DIRS}
   )

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GSL DEFAULT_MSG GSL_LIBRARIES)
MARK_AS_ADVANCED(GSL_INCLUDE_DIR GSL_LIBRARIES GSL_XMLLINT_EXECUTABLE)
