# LibXml2
#
# LIBXML2_FOUND - System has it
# LIBXML2_INCLUDE_DIR - include directory
# LIBXML2_LIBRARIES - libraries
# LIBXML2_DEFINITIONS - Compiler flags

PKG_CHECK_MODULES(PC_LIBXML2 libxml-2.0)
SET(LIBXML2_DEFINITIONS ${PC_LIBXML2_CFLAGS_OTHER})

FIND_PATH(LIBXML2_INCLUDE_DIR NAMES libxml/xpath.h
   HINTS
   ${PC_LIBXML2_INCLUDEDIR}
   ${PC_LIBXML2_INCLUDE_DIRS}
   PATH_SUFFIXES libxml2
   )

FIND_LIBRARY(LIBXML2_LIBRARIES NAMES xml2 libxml2
   HINTS
   ${PC_LIBXML2_LIBDIR}
   ${PC_LIBXML2_LIBRARY_DIRS}
   )

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibXml2 DEFAULT_MSG LIBXML2_LIBRARIES LIBXML2_INCLUDE_DIR)

MARK_AS_ADVANCED(LIBXML2_INCLUDE_DIR LIBXML2_LIBRARIES LIBXML2_XMLLINT_EXECUTABLE)
