#  -*- mode: cmake -*-

set(TPL_MISSING FALSE)

if(NOT (LAPACK_FOUND) AND USE_LAPACK)
	message( STATUS "LAPACK will be installed!" )
	set(TPL_MISSING TRUE)
endif()
if(NOT (GLIB2_FOUND) AND USE_GLIB2)
	message( STATUS "GLIB2 will be installed!" )
	set(TPL_MISSING TRUE)
endif()
if(NOT (GSL_FOUND) AND USE_GSL)
	message( STATUS "GSL will be installed!" )
	set(TPL_MISSING TRUE)
endif()
if(NOT (LIBYAML_FOUND) AND USE_YAML)
	message( STATUS "LIBYAML will be installed!" )
	set(TPL_MISSING TRUE)
endif()
if(NOT (LIBXML2_FOUND) AND USE_XML)
	message( STATUS "LIBXML2 will be installed!" )
	set(TPL_MISSING TRUE)
endif()
if(NOT (LIBMATHEVAL_FOUND) AND USE_MATHEVAL)
	message( STATUS "LIBMATHEVAL will be installed!" )
	set(TPL_MISSING TRUE)
endif()
if(NOT (TPL_MISSING))
	message( STATUS "All TPLs required to execute MADS are available!" )
endif()
