#  -*- mode: cmake -*-

set(TPL_MISSING FALSE)

if(USE_GSL AND NOT GSL_FOUND)
set(TPL_MISSING TRUE)
endif()

if(USE_LAPACK AND NOT LAPACK_FOUND)
set(TPL_MISSING TRUE)
endif()

if(USE_BLAS AND NOT BLAS_FOUND)
set(TPL_MISSING TRUE)
endif()

if(USE_ATLAS AND NOT ATLAS_FOUND)
set(TPL_MISSING TRUE)
endif()

if(USE_LIBXML2 AND NOT LIBXML2_FOUND)
set(TPL_MISSING TRUE)
endif()

if(USE_LIBMATHEVAL AND NOT LIBMATHEVAL_FOUND)
set(TPL_MISSING TRUE)
endif()
