#  -*- mode: cmake -*-
if(USE_HTTPS)
    set(HTTP "https://")
else()
    set(HTTP "http://")
endif()

set(LAPACK_VERSION_MAJOR 3)
set(LAPACK_VERSION_MINOR 5.0)
set(LAPACK_VERSION ${LAPACK_VERSION_MAJOR}.${LAPACK_VERSION_MINOR})
set(LAPACK_ARCHIVE_FILE lapack-${LAPACK_VERSION}.tgz)
set(LAPACK_URL_SITE "www.netlib.org/lapack")
string(CONCAT LAPACK_URL_STRING ${HTTP} ${LAPACK_URL_SITE} )

set(GSL_VERSION_MAJOR 1)
set(GSL_VERSION_MINOR 16)
set(GSL_VERSION ${GSL_VERSION_MAJOR}.${GSL_VERSION_MINOR})
if(USE_HTTPS)
   set(GSL_URL_STRING     "https://ftp.gnu.org/gnu/gsl")
else()
   set(GSL_URL_STRING     "http://ftp.gnu.org/gnu/gsl")
endif()
set(GSL_ARCHIVE_FILE   gsl-${GSL_VERSION}.tar.gz)

set(GLIB2_VERSION_MAJOR 2)
set(GLIB2_VERSION_MINOR 40.0)
set(GLIB2_VERSION ${GLIB2_VERSION_MAJOR}.${GLIB2_VERSION_MINOR})
set(GLIB2_ARCHIVE_FILE   glib-${GLIB2_VERSION}.zip)
set(GLIB2_URL_SITE "git.gnome.org/browse/glib/snapshot")
string(CONCAT GLIB2_URL_STRING ${HTTP} ${GLIB2_URL_SITE} )
print_var( GLIB2_URL_STRING )

set(LIBMATHEVAL_VERSION_MAJOR 1)
set(LIBMATHEVAL_VERSION_MINOR 1.11)
set(LIBMATHEVAL_VERSION ${LIBMATHEVAL_VERSION_MAJOR}.${LIBMATHEVAL_VERSION_MINOR})
if(USE_HTTPS)
   set(LIBMATHEVAL_URL_STRING     "https://ftp.gnu.org/gnu/libmatheval")
else()
   set(LIBMATHEVAL_URL_STRING     "http://ftp.gnu.org/gnu/libmatheval")
endif()
set(LIBMATHEVAL_ARCHIVE_FILE   libmatheval-${LIBMATHEVAL_VERSION}.tar.gz)
